version: "3"
services:
    banco-dados:
        container_name: bd-postgres
        image:
            postgres
        env_file:
            - .env
        expose:
            - $
        ports:
            - "5434:5432"
        restart: always
        volumes:
            - ./bd-postgres:/db/postgres
    aiko-next:
        container_name: aiko-next
        build:
            context: ./aiko-next
            dockerfile: Dockerfile
            args:
                - 
        restart: always
        ports:
            - "8000:8000"
        stop_signal: SIGINT
        env_file:
            - .env
volumes:
    bd-postgres: